### ISSUE TITLE
Original data are not actually zeroed

### ISSUE THREAD

**Issue by oblique** [quininer/seckey#4]
Consider this example:

```rust
use seckey::SecKey;

fn main() {
    let buf: [u8; 7] = [1, 2, 3, 4, 5, 6, 7];
    let orig_data = unsafe { std::slice::from_raw_parts(buf.as_ptr(), buf.len()) };

    let sec = SecKey::new(buf).unwrap();

    dbg!(orig_data);
}
```

Because `buf` is an array, by moving it, you are actually copying it to another place on the stack. So, original data stay there untouched and never zeroed.

I was thinking that `&mut T` could be a solution, but this will make `SecKey` unsafe.
What do you think?

**Comment by quininer** [comment]
A few years ago I tried to solve this problem with [inplace syntax](https://github.com/rust-lang/rust/issues/27779), which has been deprecated.

**Comment by quininer** [comment]
close by 0.11
